config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"

  # CRUD actions / routes for items
  resources :items do
    member do
      post 'toggle_favorite', to: "items#toggle_favorite"
    end
  end

  # Shows user's food/ingredient items
  get "my-items", to: "items#my_items", as: :my_items

  # Creates requests for giver and receiver to send messages
  resources :requests, only: %i[show index create] do
    post "messages", to: "messages#create"
  end

  # Creates feedback for the end of messages between users.
  resources :messages, only: %i[new create] do
    get "feedbacks/new", to: "feedbacks#new"
    post "feedbacks", to: "feedbacks#create"
  end

  # resources :profiles, only: %i[show edit update]
  get '/my-profile', to: 'profiles#my_profile', as: :my_profile

  get '/my-favorites', to: 'pages#my_favorites', as: :my_favorites
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def my_profile
    # Gets current user coordinates, currently using static postal code until we fix the Js issue.
    @current_postal_code = 'Montreal, Av. casgrain'

    # Distance between current user and other users (for index cards).
    @distances_between_other_users = {}

    @profile = User.find(current_user.id)

    # Items that the current user has requested.
    @items = Item.joins(:requests).where(requests: {receiver_id: current_user.id }).order(:status)

    # All users where the request receiver is the current user
    @users = User.joins(:requests_as_giver).where(requests_as_giver: { receiver_id: current_user.id })

    # Sets distance for each user that's nearby, private method below.
    get_distance(@users)
  end

  private

  # Sets distance for each user that's nearby.
  def get_distance(users)
    # users = User.all
    current_coordinates = Geocoder.coordinates(@current_postal_code)
    users.each do |user|
      total_distance = user.distance_from(current_coordinates).round(1)
      @distances_between_other_users[user.id] = total_distance
    end
  end
end

app/views/profiles/my_profile.html.erb
<div class="profile d-flex flex-column align-items-center">
  <%= image_tag "demo_user.png", class: 'avatar-large shadow' %>
  <%# <div class="text-decoration-underline my-2">
    <%= link_to "Edit", "#", class: 'edit-link' %>
  <%# </div> %>
  <div class="buttons my-5 justify-content-center">
    <div><%= link_to "My items", my_items_path,  class:"btn btn-flat" %></div>
  </div>
  <div class="requests item-profile">
    <div class="heading">
      <h5>Requested items</h5>
    </div>
    <!-- Cards-->
          <div class="cards items my-4" id="cards-items">
            <% @items.each do |item| %>
              <%= link_to item_path(item), class: "text-decoration-none" do%>
                <div class="card-product <%= ('donated' if item.donated?) || ('reserved' if item.reserved?) %>">
                  <div class="image">
                    <%= cl_image_tag item.photos.first.key, class: "img" %>
                  </div>

                  <div class="card-product-infos">
                    <h2><%= item.name.capitalize %></h2>
                    <% if item.donated? %>
                      <h3>This item was donated.</h3>
                    <% elsif item.reserved? %>
                      <h3>This item is reserved.</h3>
                    <% else %>
                      <h3><%= truncate(item.description, :length => 61) %></h3>
                    <% end %>
                    <div class="d-flex card-location">
                      <strong><p><%= "#{@distances_between_other_users[item.user.id]} km" %></p></strong>
                      <p><i class="fas fa-map-marker-alt ms-3"></i>&nbsp<%= truncate(item.user.address, :length => 30) %></p>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
  </div>

  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "logout" %>
</div>

app/views/profiles/show.html.erb
<div class="profile container d-flex flex-column align-items-center">
  <%= image_tag "demo_user.png", class: 'avatar-large shadow' %>
  <div class="text-decoration-underline my-2">
    <%= link_to "Edit", edit_profile_path(@profile), class: 'edit-link' %>
  </div>
  <div class="buttons">
    <div><%= link_to "Add an item", new_item_path, class: "button" %></div>
    <div><%= link_to "My items", "#", class: "button" %></div>
    <div><%= link_to "My favorites", "#", class: "button" %></div>
  </div>
</div>