config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"

  # CRUD actions / routes for items
  resources :items do
    member do
      post 'toggle_favorite', to: "items#toggle_favorite"
    end
  end

  # Shows user's food/ingredient items
  get "my-items", to: "items#my_items", as: :my_items

  # Creates requests for giver and receiver to send messages
  resources :requests, only: %i[show index create] do
    post "messages", to: "messages#create"
  end

  # Creates feedback for the end of messages between users.
  resources :messages, only: %i[new create] do
    get "feedbacks/new", to: "feedbacks#new"
    post "feedbacks", to: "feedbacks#create"
  end

  # resources :profiles, only: %i[show edit update]
  get '/my-profile', to: 'profiles#my_profile', as: :my_profile

  get '/my-favorites', to: 'pages#my_favorites', as: :my_favorites
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-bottom navbar-expand-sm navbar-light navbar-lewagon">
  <%# 4 icons + one collapse button in the navbar %>
  <div class="container-fluid">
    <%# add class container inside link, which includes icon %>
    <%# each container should be of width 20% %>
    <%# border color as bar; background %>
    <%= active_link_to items_path, active: :exact, class: "nav-item-container" do %>
      <i class="fas fa-search"></i>
    <% end %>
    <%= active_link_to new_item_path, active: :exact, class: "nav-item-container" do %>
      <i class="far fa-plus-square"></i>
    <% end %>
    <%= active_link_to requests_path, active: :exact, class: "nav-item-container" do %>
      <i class="far fa-comment"></i>
    <% end %>
    <%= active_link_to my_favorites_path, active: :exact, class: "nav-item-container" do %>
      <i class="far fa-heart"></i>
    <% end %>
    <%= active_link_to my_profile_path, active: :exact, class: "nav-item-container" do %>
      <i class="far fa-user"></i>
    <% end %>
  </div>
</div>