config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"

  # CRUD actions / routes for items
  resources :items do
    member do
      post 'toggle_favorite', to: "items#toggle_favorite"
    end
  end

  # Shows user's food/ingredient items
  get "my-items", to: "items#my_items", as: :my_items

  # Creates requests for giver and receiver to send messages
  resources :requests, only: %i[show index create] do
    post "messages", to: "messages#create"
  end

  # Creates feedback for the end of messages between users.
  resources :messages, only: %i[new create] do
    get "feedbacks/new", to: "feedbacks#new"
    post "feedbacks", to: "feedbacks#create"
  end

  # resources :profiles, only: %i[show edit update]
  get '/my-profile', to: 'profiles#my_profile', as: :my_profile

  get '/my-favorites', to: 'pages#my_favorites', as: :my_favorites
end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id              :bigint           not null, primary key
#  description     :text
#  expiration_date :date
#  item_type       :string
#  name            :string
#  status          :integer          default("available")
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  user_id         :bigint           not null
#
class Item < ApplicationRecord
  # Associations
  acts_as_favoritable
  belongs_to :user
  has_many :items_diets, dependent: :destroy
  has_many :diets, through: :items_diets
  has_many :items_allergens, dependent: :destroy
  has_many :allergens, through: :items_allergens
  has_many :requests, dependent: :destroy
  has_many_attached :photos

  # Validations
  validates_presence_of :user_id, :photos, :description, :expiration_date, :item_type, :status, :name
  validates :description, length: { minimum: 7 }
  validates :name, length: { minimum: 3 }
  validate :expiration_date_cannot_be_in_the_past

  def expiration_date_cannot_be_in_the_past
    errors.add(:expiration_date, "can't be in the past.") if expiration_date.present? && expiration_date < Date.today
  end

  TYPES = %w[meal ingredient]
  validates :item_type, inclusion: { in: TYPES }

  # Ex: READ instance using `item.reserved?`(boolean) and WRITE using `item.donated!`
  enum status: {
    available: 0,
    reserved: 1,
    donated: 2
  }

  # added "pg_search" gem to filter the index
  include PgSearch::Model
  multisearchable against: %i[name description item_type]

  # pg_search_scope :search_index,
  #   against: %i[name description item_type],
  #   associated_against: { user: :username },
  #   using: { tsearch: { prefix: true } }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # a user doesn't have to log in to visit the index and show pages
  skip_before_action :authenticate_user!, only: :index
  # a user has to log in to like an item
  before_action :find_item, only: %i[show update toggle_favorite]

  def index
    # Get postal code from params (default to 'Montreal, Av. casgrain')
    # @postal_code = params[:item] ? params[:item][:postal_code] : 'Montreal, Av. casgrain'
    @postal_code = 'Montreal, Av. casgrain'

    # Get all users who have at least one item
    users_with_items = User.all.select {|u| u.items.count > 0}

    # Get all users near the postal_code
    @users = User.where(id: users_with_items.map(&:id)).near(@postal_code, 50)

    # Get the list of all available/reserved items of these users
    @items = @users.map(&:items).flatten.select { |item| item.available? || item.reserved? }

    # Filter items if there is a search query
    # search by (case insensitive):
    # item: name/description/type, allergen: name, diet: name (refer to models)
    if params[:query].present?
      results = PgSearch.multisearch(params[:query])
      if results.empty?
        # items mapped by postal code + status
        @items = []
      else
        @searched_items = []
        results.map do |result|
          case result[:searchable_type]
          when "Item" then @searched_items << Item.find(result[:searchable_id])
          when "User" then @searched_items += User.find(result[:searchable_id]).items
          when "Allergen" then @searched_items += Allergen.find(result[:searchable_id]).items
          when "Diet" then @searched_items += Diet.find(result[:searchable_id]).items
          end
        end
        @items = Item.where(id: @items.map(&:id)).select { |item| @searched_items.include?(item) }
      end
    end

    # Geocoder
    @markers = []
    @distances_between_other_users = {}
    get_distance
    @geocoded_users = User.geocoded
    @markers = @geocoded_users.map do |user|
      {
        lat: user.latitude,
        lng: user.longitude,
        info_window: render_to_string(
          partial: "info_window",
          locals: { user: user }
        ),
        image_url: helpers.asset_url("map_icon.png")
      }
    end

    # Stimulus controller (MUST be below Geocoder, otherwise markers won't show)
    @items_with_address = @items.map { |item| [item, item.user.address, @distances_between_other_users[item.user.id]] }
  end

  def show
    @diets = @item.diets
    @allergens = @item.allergens
    # link the show page to a new or existing request
    if Request.find_by(item_id: @item.id, receiver_id: current_user.id, giver_id: @item.user.id)
      @request = Request.find_by(item_id: @item.id, receiver_id: current_user.id, giver_id: @item.user.id)
    else
      @request = Request.new
    end

    # For the map
    user = @item.user
    @markers = [
      {
        lat: user.latitude,
        lng: user.longitude,
        info_window: render_to_string(
          partial: "info_window",
          locals: { user: user }
        ),
        image_url: helpers.asset_url("map_icon.png")
      }
    ]
  end


  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      add_allergens?
      add_diets?
      redirect_to item_path(@item)
    else
      render :new
    end
  end

  def toggle_favorite
    current_user.favorited?(@item) ? current_user.unfavorite(@item) : current_user.favorite(@item)
  end

  def my_items
    @my_available_items = Item.where(user: current_user, status: "available")
    @my_donated_items = Item.where(user: current_user, status: "donated")
    @my_reserved_items = Item.where(user: current_user, status: "reserved")
  end

  def update
    @item.update(item_params)
    redirect_to my_items_path
  end

  private

  def find_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :expiration_date, :status, :item_type, :allergens, :diets, photos: [])
  end

  def add_allergens?
    params[:item][:allergens][1...].each do |allergen|
      if Allergen.find_by(name: allergen)
        ItemsAllergen.create!(item: @item, allergen: Allergen.find_by(name: allergen))
      else
        ItemsAllergen.create!(item: @item, allergen: Allergen.create!(name: allergen))
      end
    end
  end

  def add_diets?
    params[:item][:diets][1...].each do |diet|
      if Diet.find_by(name: diet)
        ItemsDiet.create!(item: @item, diet: Diet.find_by(name: diet))
      else
        ItemsDiet.create!(item: @item, diet: Diet.create!(name: diet))
      end
    end
  end

  # Sets distance for each user that's nearby.
  def get_distance
    @current_coordinates = Geocoder.coordinates(@postal_code)
    @users.each do |user|
      total_distance = user.distance_from(@current_coordinates).round(1)
      @distances_between_other_users[user.id] = total_distance
    end
  end
end

app/views/items/_form.html.erb
<div class="new-item">
  <div class="heading">
    <h5>Add a new food item</h5>
  </div>
  <div class="container px-4 py-4 mb-5">
    <%= simple_form_for @item do |f| %>
      <%= f.input :name, placeholder: 'Name (minimum 3 characters)', label: false, class: 'w-100' %>
      <div class="d-flex justify-content-between type">
        <%= f.input_field :item_type, as: :radio_buttons, collection: Item::TYPES %>
      </div>
      <p></p>
      <%= f.input :description, label: false, placeholder: 'Description (minimum 7 characters)', class: 'w-100' %>
      <%# a new item must be available so giver doesn't need to see it in this form %>
      <%# <%= f.input :status, collection: Item.statuses.keys %>
      <%= f.input :allergens, label: 'Allergens (if any):', class: 'w-100', collection: Allergen::NAMES, input_html: { multiple: true } %>
      <%= f.input :diets, label: 'Special diets (if any):', class: 'w-100', collection: Diet::NAMES, input_html: { multiple: true } %>
      <%= f.input :expiration_date, placeholder: 'Expiration date', as: :date, html5: true, class: 'w-100' %>
      <%= f.input :photos, label: false, as: :file, input_html: { multiple: true }, class: 'w-100' %>
      <p></p>
      <div class="d-flex justify-content-center">
        <%= f.submit 'Share it!', class: 'submit-button', data: { disable_with: "Sharing..." } %>
      </div>
    <% end %>
  </div>
</div>

app/views/items/_info_window.html.erb
<h6><strong><%= user.username.capitalize %></strong> is giving away</h6>
<% user.items.each do |item|%>
  <p><%= link_to (item.name.capitalize), item_path(item) %></p>
  <%= cl_image_tag item.photos.first.key, width: "100%", height: 100 %>
  <% unless item.allergens.empty? %>
    <i class="fas fa-exclamation-triangle"></i>
    <%= item.allergens.map { |allergen| allergen.name.capitalize }.join(", ") %>
  <% end %>
  <p></p>
  <% unless item.diets.empty? %>
    <i class="fab fa-envira"></i>
    <%= item.diets.map { |diet| diet.name.capitalize }.join(", ") %>
  <% end %>
<% end %>

app/views/items/index.html.erb
<div class="items-page-container" data-controller="postal-code">
  <!-- Landing page popup -->
  <div class="initial-screen d-none" data-postal-code-target="popup">
    <div class="image-banner"></div>
    <div class="title-banner">
      <h1 style="color:#814B67">Food4<span><strong>All</strong></span></h1>
    </div>

    <div class="white-banner-container">
      <div class="white-banner">
        <p>Too much food? Share it.</p>
      </div>
    </div>

    <div class="modal-popup-container input-group mb-3" id="popup-container">
      <%= form_for :item, html: { method: 'GET' }, url: '/' do |f| %>
        <%= f.text_field :postal_code, placeholder:"Enter your zip code...", id:"postal_code", class:"form-control", html: {data: { target: "input" }} %>
        <%= f.submit "Let's start", class:"btn btn-flat", data: { action: "click->postal-code#remove", disable_with: "Searching..." } %>
       <% end %>
    </div>
  </div>




  <!-- PLEASE DONT DELETE THIS DIV-->
  <%# <form class="absolute d-none">
        <label for="postal_code">Enter your postal code: </label>
        <input type="text" id="postal_code" name="postal_code" value="< params[:postal_code] >" placeholder="Type something">
        <button name="button" id="btn" type="submit">Submit</button>
  </form> %>
  <!-- KEEP THE DIV ABOVE-->

  <!-- Navbar to switch tab -->
  <div class="navbar-container">
    <nav>
      <div class="nav nav-tabs tabs-underlined" id="nav-tab" role="tablist">
        <button class="nav-link tab-underlined active" id="nav-see-items-tab" data-bs-toggle="tab" data-bs-target="#nav-see-items" type="button" role="tab" aria-controls="nav-see-items" aria-selected="true">List food</button>
        <button class="nav-link tab-underlined" id="nav-see-map-tab" data-bs-toggle="tab" data-bs-target="#nav-see-map" type="button" role="tab" aria-controls="nav-see-map" aria-selected="false">Items on map</button>
      </div>
    </nav>
  </div>
  <!-- Covid notices-->
  <div class="special-alert-container">
    <div class="special-alert alert-success" role="alert">
      <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
      <h4 class="alert-heading">How to share safely during COVID-19?</h4>
      <hr>
      <p class="mb-0"><ul>
        <li>Consider wearing a mask</li>
        <li>Stay at home if you think you present symptoms</li>
        <li>Wash and sanitize your hands regularly</li>
      </ul></p>
    </div>
  </div>

  <!-- Search form-->
  <form>
    <div class="search-form-control form-group">
      <input class="form-control string required" name="query" id="query" value="<%= params[:query] %>" placeholder="What are you looking for?">
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
  </form>


  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade" id="nav-see-map" role="tabpanel" aria-labelledby="nav-see-map-tab">
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-see-map" role="tabpanel" aria-labelledby="nav-see-map-tab">
        <br>
          <!-- Geocoder-->
          <div id="map" style="width: 100%; height: 300px;"
            data-controller="mapbox"
            data-mapbox-markers-value="<%= @markers.to_json %>"
            data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
      </div>
    </div>

    <div class="tab-pane fade show active" id="nav-see-items" role="tabpanel" aria-labelledby="nav-see-items-tab">
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-see-items" role="tabpanel" aria-labelledby="nav-see-items-tab">
        <br>
          <!-- Cards-->
          <div class="cards items" id="cards-items" data-postal-code-target="items">
            <% @items.each do |item| %>
              <%= link_to item_path(item), class: "text-decoration-none" do%>
                <div class="card-product <%= ('donated' if item.donated?) || ('reserved' if item.reserved?) %>">
                  <div class="image">
                    <%= cl_image_tag item.photos.first.key, class: "img" %>
                  </div>

                  <div class="card-product-infos">
                    <h2><%= item.name.capitalize %></h2>
                    <% if item.donated? %>
                      <h3>This item was donated.</h3>
                    <% elsif item.reserved? %>
                      <h3>This item is reserved.</h3>
                    <% else %>
                      <h3><%= truncate(item.description, :length => 61) %></h3>
                    <% end %>
                    <div class="d-flex card-location">
                      <strong><p><%= "#{@distances_between_other_users[item.user.id]} km" %></p></strong>
                      <p><i class="fas fa-map-marker-alt ms-3"></i>&nbsp<%= truncate(item.user.address, :length => 28) %></p>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/my_items.html.erb
<div class="back-btn-container">
  <div class="back-btn">
    <%= link_to my_profile_path do %>
      <i class="fas fa-long-arrow-alt-left" aria-hidden="true" target="_blank"></i>
    <% end %>
  </div>
  <p>Back to My Profile</p>
</div>
<div class="my-items">
  <div class="heading">
    <nav>
      <div class="nav nav-tabs tabs-underlined d-flex justify-content-center" id="nav-tab" role="tablist">
        <button class="nav-link tab-underlined active" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Available</button>
        <button class="nav-link tab-underlined" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Reserved</button>
        <button class="nav-link tab-underlined" id="nav-contact-tab" data-bs-toggle="tab" data-bs-target="#nav-contact" type="button" role="tab" aria-controls="nav-contact" aria-selected="false">Donated</button>
      </div>
    </nav>
  </div>
  <div class="container my-4">
    <div class="tab-content" id="nav-tabContent">
      <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
        <% if @my_available_items.empty? %>
          <em>You don't have any available items.</em>
        <% else %>
          <div class="cards items pb-4" id="cards-items">
            <% @my_available_items.each do |item| %>
              <div class="card-product">
                <%= link_to item_path(item), class: "text-decoration-none" do %>
                  <div class="image">
                    <%= cl_image_tag item.photos.first.key, class: "img" %>
                  </div>
                <% end %>

                <div class="card-product-infos">
                  <h2><%= item.name.capitalize %></h2>
                  <h3><%= truncate(item.description, :length => 30) %></h3>
                  <%# removed the address because all my items have the same address (unimportant) %>
                  <%# <p><i class="fas fa-map-marker-alt"></i>&nbsp<%= item.user.address %>
                  <%# added button here to change status %>
                  <div class="status-form mt-2">
                    <%= simple_form_for item do |f| %>
                      <%= f.select :status, Status: Item.statuses.keys %>
                      <%= f.submit 'Update', class: 'button' %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>

      <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
        <% if @my_reserved_items.empty? %>
          <em>You don't have any reserved items.</em>
        <% else %>
          <div class="cards items pb-4" id="cards-items">

            <% @my_reserved_items.each do |item| %>
              <div class="card-product">
                <%= link_to item_path(item), class: "text-decoration-none" do %>
                  <div class="image">
                    <%= cl_image_tag item.photos.first.key, class: "img" %>
                  </div>
                <% end %>

                <div class="card-product-infos">
                  <h2><%= item.name.capitalize %></h2>
                  <h3><%= truncate(item.description, :length => 30) %></h3>
                  <%# removed the address because all my items have the same address (unimportant) %>
                  <%# <p><i class="fas fa-map-marker-alt"></i>&nbsp<%= item.user.address %>
                  <%# added button here to change status %>
                  <div class="status-form mt-2">
                    <%= simple_form_for item do |f| %>
                      <%= f.select :status, Status: Item.statuses.keys %>
                      <%= f.submit 'Update', class: 'button' %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>

      <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
        <% if @my_donated_items.empty? %>
          <em>You don't have any donated items.</em>
        <% else %>
          <div class="cards items pb-4" id="cards-items">

            <% @my_donated_items.each do |item| %>
              <div class="card-product">
                <%= link_to item_path(item), class: "text-decoration-none" do %>
                  <div class="image">
                    <%= cl_image_tag item.photos.first.key, class: "img" %>
                  </div>
                <% end %>

                <div class="card-product-infos">
                  <h2><%= item.name.capitalize %></h2>
                  <h3><%= truncate(item.description, :length => 30) %></h3>
                  <%# removed the address because all my items have the same address (unimportant) %>
                  <%# <p><i class="fas fa-map-marker-alt"></i>&nbsp<%= item.user.address %>
                  <%# added button here to change status %>
                  <div class="status-form mt-2">
                    <%= simple_form_for item do |f| %>
                      <%= f.select :status, Status: Item.statuses.keys %>
                      <%= f.submit 'Update', class: 'button' %>
                    <% end %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="back-btn-container">
  <div class="back-btn">
    <%= link_to items_path do %>
      <i class="fas fa-long-arrow-alt-left" aria-hidden="true" target="_blank"></i>
    <% end %>
  </div>
  <p>Back to listing</p>
</div>
<%= render "form", item: @item %>

app/views/items/show.html.erb
<div class="back-btn-container show">
  <div class="back-btn">
    <%= link_to items_path do %>
      <i class="fas fa-long-arrow-alt-left" aria-hidden="true" target="_blank"></i>
    <% end %>
  </div>
  <p>Back to listing</p>
</div>

<div class="container-carousel" >
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% @item.photos.each_with_index do |photo, index| %>
          <% if index == 0 %>
            <div class="carousel-item active">
              <%= cl_image_tag photo.key, class:"expand", height: 312, width: "100%" %>
            </div>
          <% else %>
            <div class="carousel-item">
              <%= cl_image_tag photo.key, class:"expand", height: 312, width: "100%" %>
            </div>
          <% end %>
        <% end %>
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>

      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>

    <div class="d-flex justify-content-between image-container">
      <%# <p class="distance"># km away</p> %>
      <div class="availability">
        <%= @item.status.capitalize %>
      </div>
      <div class="social-media" data-controller="toggle-favorite">
        <p class="distance"># km away</p>
        <div data-action="click->toggle-favorite#rose" data-toggle-favorite-target="icon">
          <%= link_to toggle_favorite_item_path(@item), remote: true, method: :post do %>
            <i class="fas fa-heart like <%= 'rose' if current_user.favorited?(@item) %>"></i>
          <% end %>
        </div>
      </div>
    </div>

</div>

<br>

<div class="container-detail">
  <div class="shadow">

    <div class="card-user">
      <% if @item.user == User.first %>
        <%= image_tag "demo_user.png", class: "avatar" %>
      <% elsif @item.user.username == 'Shayna' %>
        <%= image_tag "giver_shayna.png", class: "avatar" %>
      <% else %>
        <%= image_tag "landingpage.png", class: "avatar" %>
      <% end %>
      <div class="card-description">
        <p class="username"><%= @item.user.username.capitalize %> is giving away</p>
        <p class="item-name"> <strong><%= @item.name.capitalize %></strong></p>
        <h6><i class="fas fa-clock"></i>&nbsp Added on <%= @item.created_at.strftime("%b %e") %>&nbsp; &nbsp; &nbsp;<i class="fas fa-stopwatch"></i> Expires on <%= @item.expiration_date.strftime("%b %e") %></h6>
      </div>
    </div>

    <div class="details">
      <h6><strong>Description</strong></h6>
      <%= @item.description.capitalize %>
      <p></p>
      <% unless @allergens.empty? %>
        <i class="fas fa-exclamation-triangle"></i>
        <%= @allergens.map { |allergen| allergen.name.capitalize }.join(", ") %>
      <% end %>
      <p></p>
      <% unless @diets.empty? %>
        <i class="fab fa-envira"></i>
        <%= @diets.map { |diet| diet.name.capitalize }.join(", ") %>
      <% end %>
    </div>
  </div>

  <div class="card-category"
    id="map"
    style="width: 100%;
    height: 400px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    >
  </div>
</div>

<div class="my-5">
  <%# owner cannot request for his/her own items. %>
  <% if @item.user == current_user %>
    <em>You cannot book your own items.</em>
  <% else %>
    <%# button to link to request; using our own .button class %>
    <% if Request.find_by(item_id: @item.id, receiver_id: current_user.id, giver_id: @item.user.id) %>
      <div class="button reserve">
        <%= link_to "Back to chat", request_path(@request) %>
      </div>
    <% else %>
      <%= simple_form_for @request do |f| %>
        <%= f.hidden_field :item_id, value: @item.id %>
        <%= f.submit "Send message", class: "button reserve" %>
      <% end %>
    <% end %>
  <% end %>
</div>